// nuxt-webapp/components/Weighing.vue
<template>
  <div class="weighingDataContainer">
    <div>Сумма оценок экспертов: {{ dataToShow.sumOfMarks }}</div>
    <div>
      Относительные оценки экспертов: {{ dataToShow.relativeExpertsMarks }}
    </div>
    <div>Искомые веса: {{ dataToShow.weights }}</div>
    <div>Порядок предпочтения целей: {{ dataToShow.order }}</div>
  </div>
</template>

<script>
import { mapMutations, mapGetters, mapActions } from 'vuex'
export default {
  props: {
    solution: Object,
  },
  data() {
    return {}
  },
  computed: {
    dataToShow: function () {
      var data = {
        sumOfMarks: 0,
        relativeExpertsMarks: '',
        weights: '',
        order: '',
      }
      data.sumOfMarks = this.solution.sumOfMarks
      this.solution.relativeExpertsMarks.map((item, index) => {
        data.relativeExpertsMarks += index + 1 + ': ' + item
        if (index + 1 !== this.solution.relativeExpertsMarks.length)
          data.relativeExpertsMarks += ', '
      })
      this.solution.weights.map((item, index) => {
        data.weights += index + 1 + ': ' + item.toFixed(4)
        if (index + 1 !== this.solution.weights.length) data.weights += ', '
      })
      data.order = this.solution.order
      return data
    },
  },
}
</script>

<style>
.weighingDataContainer {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
}
</style>

// react-webapp/src/components/common/Outputs/Weighing/index.tsx
import React from 'react'
import styles from './styles.module.scss'

import { WeighingResult } from '../mocked'

const data = WeighingResult

const Weighing: React.FC = () => {
    return (
        <div className={styles.container}>
            <div className={styles.outputField}>
                <div className={styles.dataContainer}>
                    Сумма оценок экспертов:
                    {' ' + data.result.sumOfMarks}
                </div>

                <div className={styles.dataContainer}>
                    Относительные оценки экспертов:
                    {data.result.relativeExpertsMarks.map((col, i) => (
                        <div key={col} className={styles.matrixElement}>
                            {'' + (i + 1) + ': ' + col + ' '}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Искомые веса:
                    {data.result.weights.map((col, i) => (
                        <div key={col} className={styles.matrixElement}>
                            {'' + (i + 1) + ': ' + col + ' '}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Порядок предпочтения целей: {data.result.order}
                </div>
            </div>
        </div>
    )
}

export default Weighing
