// components/Weighing.vue
<template>
  <div class="weighingDataContainer">
    <div>
      Сумма оценок экспертов: {{dataToShow.sumOfMarks}}
    </div>
    <div>
      Относительные оценки экспертов: {{dataToShow.relativeExpertsMarks}}
    </div>
    <div>
      Искомые веса: {{dataToShow.weights}}
    </div>
    <div>
      Порядок предпочтения целей: {{dataToShow.order}}
    </div>
  </div>
</template>

<script>
import { mapMutations, mapGetters, mapActions } from "vuex";
export default {
    data() {
      return {
      }
    },
    computed: {
    ...mapGetters({
      weighing: "algorithms/weighing",
    }),
    dataToShow: function () {
      var data = {
        sumOfMarks: 0,
        relativeExpertsMarks: "",
        weights: "",
        order: "",
      }
      data.sumOfMarks = this.weighing.sumOfMarks
      this.weighing.relativeExpertsMarks.map((item, index) => {
        data.relativeExpertsMarks += index+1 + ": " + item
        if (index+1 !== this.weighing.relativeExpertsMarks.length)
          data.relativeExpertsMarks += ", "
      })
      this.weighing.weights.map((item, index) => {
        data.weights += index+1 + ": " + item.toFixed(4)
        if (index+1 !== this.weighing.weights.length)
          data.weights += ", "
      })
      data.order = this.weighing.order
      return data
    },
  }
}
</script>

<style>
.weighingDataContainer {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
}
</style>

// react-webapp/src/pages/CalcHistory/HOutput/methods/Weighing/index.tsx
import React from 'react'
import { WeighingResult } from '../../../../../dataTypes/resultTypes'
import styles from './styles.module.scss'

const WeighingH = (result: WeighingResult) => {

    return (
        <div className={styles.container}>
            <div className={styles.outputField}>
                <div className={styles.dataContainer}>
                    Сумма оценок экспертов: {result.sumOfMarks}
                </div>

                <div className={styles.dataContainer}>
                    Относительные оценки экспертов:
                    {result.relativeExpertsMarks.map((col, colIndex) => (
                        <div
                            key={colIndex}
                            className={styles.matrixElement}
                        >
                            {colIndex + 1 + ': ' + col + ' '}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Искомые веса:
                    {result.weights.map((col, colIndex) => (
                        <div
                            key={colIndex}
                            className={styles.matrixElement}
                        >
                            {colIndex + 1 + ': ' + col + ' '}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Порядок предпочтения целей: {result.order}
                </div>
            </div>
        </div>
    )
}

export default WeighingH
