// components/Preference.vue
<template>
  <div class="preferenceDataContainer">
    <div>
      Модифицированная матрица предпочтения: 
      <div v-for="(item) in dataToShow.modMatrix" :key="item" class="preferenceLine">
        {{item}}
      </div>
    </div>
    <div>
      Суммарные оценки предпочтения: {{dataToShow.sumMarks}}
    </div>
    <div>
      Сумма всех оценок: {{dataToShow.sumOfMarks}}
    </div>
    <div>
      Искомые веса целей: {{dataToShow.weights}}
    </div>
    <div>
      Порядок предпочтения целей: {{dataToShow.order}}
    </div>
  </div>
</template>

<script>
import { mapMutations, mapGetters, mapActions } from "vuex";
export default {
    data() {
      return {
      }
    },
    computed: {
    ...mapGetters({
      preference: "store/preference",
    }),
    dataToShow: function () {
      console.log(this.preference)
      var numOfEl = this.preference.modMatrix[0].length
      var data = {
        modMatrix: Array(this.preference.modMatrix.length).fill(""),
        sumMarks: "",
        sumOfMarks: "",
        weights: "",
        order: "",
      }
      for (var i = 0; i < this.preference.modMatrix.length; i++) {
        for (var j = 0; j < numOfEl; j++) {
          data.modMatrix[i] += this.preference.modMatrix[i][j] + " ";
        }
      }
      for (var i = 0; i < numOfEl; i++) {
        data.sumMarks += i+1 + ": " + this.preference.sumMarks[i];
        if (i+1 !== this.preference.sumMarks.length)
          data.sumMarks += " | "
      }
      for (var i = 0; i < numOfEl; i++) {
        data.weights += i+1 + ": " + this.preference.weights[i];
        if (i+1 !== this.preference.weights.length)
          data.weights += " | "
      }
      data.sumOfMarks = this.preference.sumOfMarks
      data.order = this.preference.order
      return data
    },
  }
}
</script>

<style>
.preferenceDataContainer {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
}
.preferenceLine {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  text-align: center;
}
</style>

// react-webapp/src/components/common/Outputs/Preference/index.tsx
import React from 'react'
import styles from './styles.module.scss'

import { PreferenceResult } from '../mocked'

const data = PreferenceResult

const Preference: React.FC = () => {
    return (
        <div className={styles.container}>
            <div className={styles.outputField}>
                <div className={styles.dataContainer}>
                    Модифицированная матрица предпочтения:
                    {data.result.modMatrix.map((row, i) => (
                        <div key={row[i]} className={styles.row}>
                            {row.map((col) => (
                                <div key={col} className={styles.matrixElement}>
                                    {col + ' '}
                                </div>
                            ))}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Суммарные оценки предпочтения:
                    <div className={styles.row}>
                        {data.result.sumMarks.map((col) => (
                            <div key={col} className={styles.matrixElement}>
                                {col + ' '}
                            </div>
                        ))}
                    </div>
                </div>

                <div className={styles.dataContainer}>
                    Сумма всех оценок:
                    {' ' + data.result.sumOfMarks}
                </div>

                <div className={styles.dataContainer}>
                    Искомые веса целей:
                    {data.result.weights.map((col, i) => (
                        <div key={col} className={styles.matrixElement}>
                            {'' + (i + 1) + ': ' + col + ' '}
                        </div>
                    ))}
                </div>

                <div className={styles.dataContainer}>
                    Порядок предпочтения целей:
                    {' ' + data.result.order}
                </div>
            </div>
        </div>
    )
}

export default Preference
